### ISSUE TITLE
Review source code

### ISSUE THREAD

**Issue by uveta** [ips-ag/demo-ab-testing-azure#37]
Review source code for AB testing NuGet, npm, backend and frontend.

**Comment by uveta** [comment]
NuGet fixes:
- [ ] Avoid using ```dynamic``` type, especially as API model. Probably the best option is to replace it with ```string```
- [ ] Make API models concrete. Decorate API endpoints with return type.
- [ ] Allow library user to provide their own controller implementation, in case they want to use different route, authentication, etc. Enforce implementation via interface.
- [ ] Avoid calling ```services.BuildServiceProvider()``` in extension methods, as this will initialize complete ```ServiceProvider```. Try to get App Configuration connection string using ```builder.Configuration.Get<>```

**Comment by uyen-luu** [comment]
-  Avoid using dynamic type, especially as API model. Probably the best option is to replace it with string -> [Solved](https://github.com/ips-ag/demo-ab-testing-azure/pull/43/commits/5aa01dba19f255634f5fbfafed0623c19e39e752)
- Make API models concrete. Decorate API endpoints with return type. -> [Solved](https://github.com/ips-ag/demo-ab-testing-azure/pull/43/commits/fb738039d4d46799cd020dbcc0d59a216dae0e0e)
-  Avoid calling services.BuildServiceProvider() in extension methods, as this will initialize complete ServiceProvider. Try to get App Configuration connection string using builder.Configuration.Get<> -> [Solved](https://github.com/ips-ag/demo-ab-testing-azure/pull/43/commits/bbe07af81f1407d877789d4a3abe11cf720cd70e)

_Allow library user to provide their own controller implementation, in case they want to use different route, authentication, etc. Enforce implementation via interface._

This one should already supported, by setting UseDefaultControllers = false, then the controller from Nuget would be removed and consumers can used IPSAG.AbTesting.Services.IConfigurationService to create their own controllers/logic
